package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CatPiezas generated by hbm2java
 */
public class CatPiezas implements java.io.Serializable {

	private Integer catCodigo;
	private String catNombre;
	private Set<CatEspecifica> catEspecificas = new HashSet<CatEspecifica>(0);

	public CatPiezas() {
	}

	public CatPiezas(String catNombre) {
		this.catNombre = catNombre;
	}

	public CatPiezas(String catNombre, Set<CatEspecifica> catEspecificas) {
		this.catNombre = catNombre;
		this.catEspecificas = catEspecificas;
	}

	public Integer getCatCodigo() {
		return this.catCodigo;
	}

	public void setCatCodigo(Integer catCodigo) {
		this.catCodigo = catCodigo;
	}

	public String getCatNombre() {
		return this.catNombre;
	}

	public void setCatNombre(String catNombre) {
		this.catNombre = catNombre;
	}

	public Set<CatEspecifica> getCatEspecificas() {
		return this.catEspecificas;
	}

	public void setCatEspecificas(Set<CatEspecifica> catEspecificas) {
		this.catEspecificas = catEspecificas;
	}

}
