package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

/**
 * CsLineasPedido generated by hbm2java
 */
public class CsLineasPedido implements java.io.Serializable {

	private Integer csLinCodigo;
	private Integer csPedCodigo;
	private Integer csPieCodigo;
	private String csLinDescripcion;
	private Integer csLinCantidad;
	private Float csLinPrecio;

	public CsLineasPedido() {
	}

	public CsLineasPedido(Integer csPedCodigo, Integer csPieCodigo,
			String csLinDescripcion, Integer csLinCantidad, Float csLinPrecio) {
		this.csPedCodigo = csPedCodigo;
		this.csPieCodigo = csPieCodigo;
		this.csLinDescripcion = csLinDescripcion;
		this.csLinCantidad = csLinCantidad;
		this.csLinPrecio = csLinPrecio;
	}

	public Integer getCsLinCodigo() {
		return this.csLinCodigo;
	}

	public void setCsLinCodigo(Integer csLinCodigo) {
		this.csLinCodigo = csLinCodigo;
	}

	public Integer getCsPedCodigo() {
		return this.csPedCodigo;
	}

	public void setCsPedCodigo(Integer csPedCodigo) {
		this.csPedCodigo = csPedCodigo;
	}

	public Integer getCsPieCodigo() {
		return this.csPieCodigo;
	}

	public void setCsPieCodigo(Integer csPieCodigo) {
		this.csPieCodigo = csPieCodigo;
	}

	public String getCsLinDescripcion() {
		return this.csLinDescripcion;
	}

	public void setCsLinDescripcion(String csLinDescripcion) {
		this.csLinDescripcion = csLinDescripcion;
	}

	public Integer getCsLinCantidad() {
		return this.csLinCantidad;
	}

	public void setCsLinCantidad(Integer csLinCantidad) {
		this.csLinCantidad = csLinCantidad;
	}

	public Float getCsLinPrecio() {
		return this.csLinPrecio;
	}

	public void setCsLinPrecio(Float csLinPrecio) {
		this.csLinPrecio = csLinPrecio;
	}

}
