package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CsPedidos generated by hbm2java
 */
public class CsPedidos implements java.io.Serializable {

	private int csCodPedido;
	private String csEstado;
	private Float csImporte;
	private Date csFechaHora;
	private Date csFechaHoraEliminado;
	private Integer csUserCodigo;
	private String csNombreUser;
	private String csApellidosUser;

	public CsPedidos() {
	}

	public CsPedidos(int csCodPedido) {
		this.csCodPedido = csCodPedido;
	}

	public CsPedidos(int csCodPedido, String csEstado, Float csImporte,
			Date csFechaHora, Date csFechaHoraEliminado, Integer csUserCodigo,
			String csNombreUser, String csApellidosUser) {
		this.csCodPedido = csCodPedido;
		this.csEstado = csEstado;
		this.csImporte = csImporte;
		this.csFechaHora = csFechaHora;
		this.csFechaHoraEliminado = csFechaHoraEliminado;
		this.csUserCodigo = csUserCodigo;
		this.csNombreUser = csNombreUser;
		this.csApellidosUser = csApellidosUser;
	}

	public int getCsCodPedido() {
		return this.csCodPedido;
	}

	public void setCsCodPedido(int csCodPedido) {
		this.csCodPedido = csCodPedido;
	}

	public String getCsEstado() {
		return this.csEstado;
	}

	public void setCsEstado(String csEstado) {
		this.csEstado = csEstado;
	}

	public Float getCsImporte() {
		return this.csImporte;
	}

	public void setCsImporte(Float csImporte) {
		this.csImporte = csImporte;
	}

	public Date getCsFechaHora() {
		return this.csFechaHora;
	}

	public void setCsFechaHora(Date csFechaHora) {
		this.csFechaHora = csFechaHora;
	}

	public Date getCsFechaHoraEliminado() {
		return this.csFechaHoraEliminado;
	}

	public void setCsFechaHoraEliminado(Date csFechaHoraEliminado) {
		this.csFechaHoraEliminado = csFechaHoraEliminado;
	}

	public Integer getCsUserCodigo() {
		return this.csUserCodigo;
	}

	public void setCsUserCodigo(Integer csUserCodigo) {
		this.csUserCodigo = csUserCodigo;
	}

	public String getCsNombreUser() {
		return this.csNombreUser;
	}

	public void setCsNombreUser(String csNombreUser) {
		this.csNombreUser = csNombreUser;
	}

	public String getCsApellidosUser() {
		return this.csApellidosUser;
	}

	public void setCsApellidosUser(String csApellidosUser) {
		this.csApellidosUser = csApellidosUser;
	}

}
