package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas implements java.io.Serializable {

	private Integer marCodigo;
	private String marNombre;
	private Set<Modelos> modeloses = new HashSet<Modelos>(0);

	public Marcas() {
	}

	public Marcas(String marNombre) {
		this.marNombre = marNombre;
	}

	public Marcas(String marNombre, Set<Modelos> modeloses) {
		this.marNombre = marNombre;
		this.modeloses = modeloses;
	}

	public Integer getMarCodigo() {
		return this.marCodigo;
	}

	public void setMarCodigo(Integer marCodigo) {
		this.marCodigo = marCodigo;
	}

	public String getMarNombre() {
		return this.marNombre;
	}

	public void setMarNombre(String marNombre) {
		this.marNombre = marNombre;
	}

	public Set<Modelos> getModeloses() {
		return this.modeloses;
	}

	public void setModeloses(Set<Modelos> modeloses) {
		this.modeloses = modeloses;
	}

}
