package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Modelos generated by hbm2java
 */
public class Modelos implements java.io.Serializable {

	private Integer modCodigo;
	private Marcas marcas;
	private String modNombre;
	private Set<Tipos> tiposes = new HashSet<Tipos>(0);

	public Modelos() {
	}

	public Modelos(String modNombre) {
		this.modNombre = modNombre;
	}

	public Modelos(Marcas marcas, String modNombre, Set<Tipos> tiposes) {
		this.marcas = marcas;
		this.modNombre = modNombre;
		this.tiposes = tiposes;
	}

	public Integer getModCodigo() {
		return this.modCodigo;
	}

	public void setModCodigo(Integer modCodigo) {
		this.modCodigo = modCodigo;
	}

	public Marcas getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Marcas marcas) {
		this.marcas = marcas;
	}

	public String getModNombre() {
		return this.modNombre;
	}

	public void setModNombre(String modNombre) {
		this.modNombre = modNombre;
	}

	public Set<Tipos> getTiposes() {
		return this.tiposes;
	}

	public void setTiposes(Set<Tipos> tiposes) {
		this.tiposes = tiposes;
	}

}
