package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PedidosProveedor generated by hbm2java
 */
public class PedidosProveedor implements java.io.Serializable {

	private Integer pedproCodigo;
	private Piezas piezas;
	private Proveedores proveedores;
	private String pedproProNombre;
	private String pedproPieNombre;
	private Integer pedproCantidad;
	private String pedproComentarios;
	private Date pedproFechaHora;

	public PedidosProveedor() {
	}

	public PedidosProveedor(Piezas piezas, Proveedores proveedores,
			String pedproProNombre, String pedproPieNombre,
			Integer pedproCantidad, String pedproComentarios,
			Date pedproFechaHora) {
		this.piezas = piezas;
		this.proveedores = proveedores;
		this.pedproProNombre = pedproProNombre;
		this.pedproPieNombre = pedproPieNombre;
		this.pedproCantidad = pedproCantidad;
		this.pedproComentarios = pedproComentarios;
		this.pedproFechaHora = pedproFechaHora;
	}

	public Integer getPedproCodigo() {
		return this.pedproCodigo;
	}

	public void setPedproCodigo(Integer pedproCodigo) {
		this.pedproCodigo = pedproCodigo;
	}

	public Piezas getPiezas() {
		return this.piezas;
	}

	public void setPiezas(Piezas piezas) {
		this.piezas = piezas;
	}

	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	public String getPedproProNombre() {
		return this.pedproProNombre;
	}

	public void setPedproProNombre(String pedproProNombre) {
		this.pedproProNombre = pedproProNombre;
	}

	public String getPedproPieNombre() {
		return this.pedproPieNombre;
	}

	public void setPedproPieNombre(String pedproPieNombre) {
		this.pedproPieNombre = pedproPieNombre;
	}

	public Integer getPedproCantidad() {
		return this.pedproCantidad;
	}

	public void setPedproCantidad(Integer pedproCantidad) {
		this.pedproCantidad = pedproCantidad;
	}

	public String getPedproComentarios() {
		return this.pedproComentarios;
	}

	public void setPedproComentarios(String pedproComentarios) {
		this.pedproComentarios = pedproComentarios;
	}

	public Date getPedproFechaHora() {
		return this.pedproFechaHora;
	}

	public void setPedproFechaHora(Date pedproFechaHora) {
		this.pedproFechaHora = pedproFechaHora;
	}

}
