package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores implements java.io.Serializable {

	private Integer proCodigo;
	private String proNombre;
	private String proTelefono;
	private String proDireccion;
	private String proNumcuenta;
	private Set<Piezas> piezases = new HashSet<Piezas>(0);
	private Set<PedidosProveedor> pedidosProveedors = new HashSet<PedidosProveedor>(
			0);
	private Set<Piezas> piezases_1 = new HashSet<Piezas>(0);

	public Proveedores() {
	}

	public Proveedores(String proNombre) {
		this.proNombre = proNombre;
	}

	public Proveedores(String proNombre, String proTelefono,
			String proDireccion, String proNumcuenta, Set<Piezas> piezases,
			Set<PedidosProveedor> pedidosProveedors, Set<Piezas> piezases_1) {
		this.proNombre = proNombre;
		this.proTelefono = proTelefono;
		this.proDireccion = proDireccion;
		this.proNumcuenta = proNumcuenta;
		this.piezases = piezases;
		this.pedidosProveedors = pedidosProveedors;
		this.piezases_1 = piezases_1;
	}

	public Integer getProCodigo() {
		return this.proCodigo;
	}

	public void setProCodigo(Integer proCodigo) {
		this.proCodigo = proCodigo;
	}

	public String getProNombre() {
		return this.proNombre;
	}

	public void setProNombre(String proNombre) {
		this.proNombre = proNombre;
	}

	public String getProTelefono() {
		return this.proTelefono;
	}

	public void setProTelefono(String proTelefono) {
		this.proTelefono = proTelefono;
	}

	public String getProDireccion() {
		return this.proDireccion;
	}

	public void setProDireccion(String proDireccion) {
		this.proDireccion = proDireccion;
	}

	public String getProNumcuenta() {
		return this.proNumcuenta;
	}

	public void setProNumcuenta(String proNumcuenta) {
		this.proNumcuenta = proNumcuenta;
	}

	public Set<Piezas> getPiezases() {
		return this.piezases;
	}

	public void setPiezases(Set<Piezas> piezases) {
		this.piezases = piezases;
	}

	public Set<PedidosProveedor> getPedidosProveedors() {
		return this.pedidosProveedors;
	}

	public void setPedidosProveedors(Set<PedidosProveedor> pedidosProveedors) {
		this.pedidosProveedors = pedidosProveedors;
	}

	public Set<Piezas> getPiezases_1() {
		return this.piezases_1;
	}

	public void setPiezases_1(Set<Piezas> piezases_1) {
		this.piezases_1 = piezases_1;
	}

}
