package clases;

// Generated 28-ene-2015 16:17:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipos generated by hbm2java
 */
public class Tipos implements java.io.Serializable {

	private Integer tipCodigo;
	private Modelos modelos;
	private String tipDescripcion;
	private Set<Piezas> piezases = new HashSet<Piezas>(0);

	public Tipos() {
	}

	public Tipos(Modelos modelos, String tipDescripcion, Set<Piezas> piezases) {
		this.modelos = modelos;
		this.tipDescripcion = tipDescripcion;
		this.piezases = piezases;
	}

	public Integer getTipCodigo() {
		return this.tipCodigo;
	}

	public void setTipCodigo(Integer tipCodigo) {
		this.tipCodigo = tipCodigo;
	}

	public Modelos getModelos() {
		return this.modelos;
	}

	public void setModelos(Modelos modelos) {
		this.modelos = modelos;
	}

	public String getTipDescripcion() {
		return this.tipDescripcion;
	}

	public void setTipDescripcion(String tipDescripcion) {
		this.tipDescripcion = tipDescripcion;
	}

	public Set<Piezas> getPiezases() {
		return this.piezases;
	}

	public void setPiezases(Set<Piezas> piezases) {
		this.piezases = piezases;
	}

}
